---
title: "Problembehandlung bei Ausnahmen: System.Workflow.Runtime.WorkflowOwnershipException"
ms.custom: na
ms.date: "10/29/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: na
ms.suite: na
ms.technology: 
  - "devlang-csharp"
ms.tgt_pltfrm: na
ms.topic: "article"
f1_keywords: 
  - "EHWRWorkflowOwnership"
helpviewer_keywords: 
  - "System.Workflow.Runtime.WorkflowOwnershipException-Ausnahme"
  - "WorkflowOwnershipException-Ausnahme"
ms.assetid: 20291283-dfc8-4e34-b84d-f380e04be376
caps.latest.revision: 7
caps.handback.revision: "7"
ms.author: "mblome"
manager: "douge"
---
# Problembehandlung bei Ausnahmen: System.Workflow.Runtime.WorkflowOwnershipException
Eine <xref:System.Workflow.Runtime.WorkflowOwnershipException>\-Ausnahme wird ausgelöst, wenn das Workflow\-Laufzeitmodul versucht, eine Workflowinstanz zu laden, die derzeit von einer anderen Instanz des Workflow\-Laufzeitmoduls geladen wird. Diese Ausnahme wird außerdem ausgelöst, wenn das Workflow\-Laufzeitmodul versucht, einen Workflow nach dem Besitztimeout zu speichern, das während dem Laden des Workflows festgelegt wurde.  
  
## Siehe auch  
 <xref:System.Workflow.Runtime.WorkflowOwnershipException>   
 [Use the Exception Assistant](../Topic/How%20to:%20Use%20the%20Exception%20Assistant.md)